### ISSUE TITLE
Greetings Sir!

### ISSUE THREAD

**Issue by ChristianCSE** [ralusek/uber-queue#2]
I was wondering when this will be available? 
I've been meaning to use this due to the praise I've been hearing; and yet, it seems not to be functional.

**Comment by holmesal** [comment]
@ChristianCSE greetings sir! I am also of the waiting with much enthuse. Unfortunately it seems to be missing. I am tired of waiting. Please fix @ralusek

**Comment by ralusek** [comment]
It's functional. It's REALLY functional. I just said it wasn't to absolve myself of responsibility.

**Comment by ChristianCSE** [comment]
I'm out here on my grind trying to make the next Uber & Airbnb but for toilets. 
It'll be on-demand-toilets whenever/where ever you need. 
I need this now kid.
